apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" .}}-secret
data:
  mongodb-uri: {{ with .Values.secret.mongodb_url -}}
  {{- list "mongodb://" .user ":" .password "@" $.Release.Name "-" .chart ":" .port "/guestbook?authSource=admin" | join "" | b64enc | quote }}
  {{- end }}
  # mongodb://admin:password@mongodb:27017/guestbook?authSource=admin