frontend:
  config:
    guestbook_name: "MyPopRock Festival 2.0"
    backend_uri: "backend.home.local/guestbook"
  ingress: 
    enable: false

backend:
  secret:
    mongodb_url:
      user: admin
      password: password
  ingress:
    enable: false

database:
  username: admin
  password: password

ingress:
  hosts:
  - host: 
      domain: frontend.home.local
      chart: frontend
  - host:
      domain: backend.home.local
      chart: backend