apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ include "frontend.fullname" . }}
  name: {{ include "frontend.fullname" . }}
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 4200
  selector:
    app: {{ include "frontend.fullname" . }}
