{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "frontend.fullname" .}}-ingress
spec:
  rules:
  {{- with .Values.ingress }}
  - host: {{ .host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
  {{- end }}
        backend:
          service: 
            name: {{ include "frontend.fullname" . }}
            port: 
              number: 80
  
{{- end }}