kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "database.fullname" .}}-pv-volume
  labels:
    type: local
spec:
  # storageClassName: manual
  capacity:
    storage: 100Mi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path:  /mnt/data
