apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.fullname" .}}-secret
data:
  mongodb-username: {{ .Values.username | b64enc | quote}}
  mongodb-password: {{ .Values.password | b64enc | quote}}