apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "database.fullname" .}}-pvc
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi